### ISSUE TITLE
[BUG] demo moas fmriprep not working since bids-matlab does not copy the timeseries.tsv file

### ISSUE THREAD

**Issue by marcobarilari** [cpp-lln-lab/bidspm#1004]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating system

- [ ] Linux
- [X] Mac
- [ ] Windows

### SPM 12 version

- [ ] 7771
- [ ] 7487
- [ ] 7219

### Platform

- [X] MATLAB
- [ ] Octave

### bidspm version

v3.0.0

### bidspm branch / commit number

- main aab3783c

### Expected Behavior

To run smoothly the demo MoAE

### Current Behavior & Error message

```matlab
% this is the error I got
[22:00:27] bidspm - INFO				
The value of 'regressorsMatFile' is invalid. It must satisfy the function: @(x)exist(x,'file')==2.
 Error MATLAB:InputParser:ArgumentFailedValidation occurred:
	- Error in regressorsMatToTsv
		line 22 in /Users/barilari/Desktop/temp/bidspm/src/IO/regressorsMatToTsv.m
	- Error in setBatchSubjectLevelGLMSpec
		line 166 in /Users/barilari/Desktop/temp/bidspm/src/batches/stats/setBatchSubjectLevelGLMSpec.m
	- Error in setAction
		line 235 in /Users/barilari/Desktop/temp/bidspm/src/workflows/stats/bidsFFX.m
	- Error in bidsFFX
		line 109 in /Users/barilari/Desktop/temp/bidspm/src/workflows/stats/bidsFFX.m
	- Error in stats
		line 347 in /Users/barilari/Desktop/temp/bidspm/demos/MoAE/../../bidspm.m
	- Error in executeAction
		line 161 in /Users/barilari/Desktop/temp/bidspm/demos/MoAE/../../bidspm.m
	- Error in bidspm
		line 79 in /Users/barilari/Desktop/temp/bidspm/demos/MoAE/../../bidspm.m

ERROR LOG SAVED:
	/Users/barilari/Desktop/temp/bidspm/demos/MoAE/outputs/derivatives/error_logs/error_2023-05-01T22-00.log
Use it when opening an issue:
	https://github.com/cpp-lln-lab/bidspm/issues/new/choose.
```

### Anything else?

Since I want to implement analyses starting from fmriprep I played with the demo first to see if I can place my `fmriprep` folder in my yoda at `/outputs/derivatives/fmriprep`. Though ...

`bids-matlab` dopes not copy the `timeseries.tsv` file (though it does copy the `timeseries.josn` one).

It must be in some latest update because resetting `bids-matlab` to a previous commit (chosen randomly but quiet recent) like `3a86a3b7393f2a73a26eda105dc61b9f4954c175` then works.

**Comment by Remi-Gau** [comment]
if you try to run bid.layout on the fmriprep dataset with `'use_schema', false`, can you at least find the file wit bids.query?

if you try to run the script but increase the verbosity to 2 or even 3 do you get more info?

**Comment by marcobarilari** [comment]
I confirm it is a mac thing since on the monster (ubuntu) it works :/. Will check later to run what you asked.

**Comment by Remi-Gau** [comment]
OK that should help narrow things down already

**Comment by Remi-Gau** [comment]
hopefully this will be solved in https://github.com/cpp-lln-lab/bidspm/pull/994

**Comment by Remi-Gau** [comment]
should now be fixed

reopen if not
