### ISSUE TITLE
[BUG] Data not found if running smoothing subject by subject with fmriprep output

### ISSUE THREAD

**Issue by marcobarilari** [cpp-lln-lab/bidspm#1006]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating system

- [X] Linux
- [ ] Mac
- [ ] Windows

### Operating system version

- Linux Ubuntu  22.04.1

### SPM 12 version

- [X] 7771
- [ ] 7487
- [ ] 7219

### Platform

- [X] MATLAB
- [ ] Octave

### Platform version

- MATLAB 2018a

### bidspm version

v3.0.0

### bidspm branch / commit number

- main 8a60b4bf

### Expected Behavior

Option to run smoothing subject by subject 

### Current Behavior & Error message

```matlab
% this is the error I got
[14:42:07] bidspm - INFO				

No subject present in dataset:
	/media/marcobarilari/DATA/marco/Data/datalad/analisys_high-re_multiSensSpatFreq/outputs/derivatives/bidspm-preproc.
Did you run bids.layout first?

 Error query:noSubjectField occurred:
	- Error in error_handling
		line 53 in /media/marcobarilari/DATA/marco/Data/datalad/analisys_high-re_multiSensSpatFreq/code/lib/bidspm/lib/bids-matlab/+bids/+internal/error_handling.m
	- Error in get_subjects
		line 331 in /media/marcobarilari/DATA/marco/Data/datalad/analisys_high-re_multiSensSpatFreq/code/lib/bidspm/lib/bids-matlab/+bids/query.m
	- Error in query
		line 185 in /media/marcobarilari/DATA/marco/Data/datalad/analisys_high-re_multiSensSpatFreq/code/lib/bidspm/lib/bids-matlab/+bids/query.m
	- Error in manage_dependencies
		line 711 in /media/marcobarilari/DATA/marco/Data/datalad/analisys_high-re_multiSensSpatFreq/code/lib/bidspm/lib/bids-matlab/+bids/layout.m
	- Error in layout
		line 205 in /media/marcobarilari/DATA/marco/Data/datalad/analisys_high-re_multiSensSpatFreq/code/lib/bidspm/lib/bids-matlab/+bids/layout.m
	- Error in getData
		line 59 in /media/marcobarilari/DATA/marco/Data/datalad/analisys_high-re_multiSensSpatFreq/code/lib/bidspm/src/IO/getData.m
	- Error in setUpWorkflow
		line 57 in /media/marcobarilari/DATA/marco/Data/datalad/analisys_high-re_multiSensSpatFreq/code/lib/bidspm/src/utils/setUpWorkflow.m
	- Error in bidsSmoothing
		line 32 in /media/marcobarilari/DATA/marco/Data/datalad/analisys_high-re_multiSensSpatFreq/code/lib/bidspm/src/workflows/preproc/bidsSmoothing.m
	- Error in smooth
		line 273 in /media/marcobarilari/DATA/marco/Data/datalad/analisys_high-re_multiSensSpatFreq/code/lib/bidspm/bidspm.m
	- Error in executeAction
		line 134 in /media/marcobarilari/DATA/marco/Data/datalad/analisys_high-re_multiSensSpatFreq/code/lib/bidspm/bidspm.m
	- Error in bidspm
		line 79 in /media/marcobarilari/DATA/marco/Data/datalad/analisys_high-re_multiSensSpatFreq/code/lib/bidspm/bidspm.m

ERROR LOG SAVED:
	/media/marcobarilari/DATA/marco/Data/datalad/analisys_high-re_multiSensSpatFreq/outputs/derivatives/error_logs/error_2023-05-02T14-42.log
Use it when opening an issue:
	https://github.com/cpp-lln-lab/bidspm/issues/new/choose.

```

### Anything else?

If I run sub-01 it is ok, then I run sub-02 and it fails.

I delete `bidsm-preproc` and run only sub-02 and it works. Then sub-01 only and it fails.

My interpretation is: 

1. I run smoothing step and it copies the selected subject into 'bidspm-preproc' (newly created since preprocessed stuff is from fmriprep) and bidspm understands that data are in `fmriprep` folder
2. I run smoothing for my second subject and now bidspm expect to have the `*-preproc*` in `bidspm-preproc` folder but they are not and it does not look into `fmriprep` folder then it stops with error

If I run all the subjects together then it works.

Does it make sense?

**Comment by marcobarilari** [comment]
Also, after smoothing eg `task-1`, when I run smoothing (as well data are from fmriprep) for `task-2` I have the same problem where `bidspm` does not find any data with the selected task (cause it is looking in `bidspm-preproc` and not in `fmriprep` folder)

**Comment by Remi-Gau** [comment]
It seems this is the problem: https://github.com/cpp-lln-lab/bidspm/blob/05d92e9ebcf854e42d2cd12db55495479704239c/bidspm.m#L271

The copy to the bidspm-preproc will only be done during smooth if the output dir does not already exist.

Possibility A (easy and slow): copy files for every smooth even if output dir is there... slow because you may copy files several times but at least you make sure that the files are there.

Possibility B: only copy the needed files.

Can you check if only keeping `copy(args);` and removing the if block solves it?

If so I would suggest to open a PR with this small change and open a separate issue to see how to implement possibility B.

**Comment by Remi-Gau** [comment]
yes open the PR and let's see what the CI says: that's why it is there, to tell us about thinks that are breaking we did not think about.
