### ISSUE TITLE
statistic model session wise

### ISSUE THREAD

**Issue by Rageve** [cpp-lln-lab/bidspm#1007]
until you'll fix the issue with the already smoothed images from fmriprep when selecting use-aroma (..._preproc_smoothAROMAnonaggr_bold.nii.gz), I continued with the standard processing of the fmriprep unsmoothed images including copying and smoothing. Now I run the statistical model with the standard motion regressors as confounds. 
Unfortunately, the first level statistic was concatenated over two session with 2 runs each (4 runs in one model). However, I would like to compute the first level model session wise (the same day/visit), that means two runs for session1 (ses-V0) and two runs for session 2 (ses-V9). 
Should I modify the Nodes flags to run this model? Currently the definition is as follows.
"Nodes": [
    {
      "Level": "Run",
      "Name": "run",
      "GroupBy": [
        "run",
        "session",
        "subject"
      ],

**Comment by Remi-Gau** [comment]
OK from the top of my head I think this is something I have not yet implemented because no one had asked for it.

Specify contrasts at the session level is not yet present here:
https://github.com/cpp-lln-lab/bidspm/blob/05d92e9ebcf854e42d2cd12db55495479704239c/src/stats/subject_level/specifyContrasts.m#L60-L74

It vaguely relates to: https://github.com/cpp-lln-lab/bidspm/issues/809

Just to be clear the way this will most likely be implemented is to have all runs in single model and then compute contrasts session wise.

**Comment by Rageve** [comment]
I think it can be a problem if lets say session 1 is placebo and  
session 2 is verum and the sessions (both two runs) are presented in  
counterbalanced order over subjects.

In this case it is easier to define the contrasts session wise and not  
combined over all runs.

Zitat von Remi Gau ***@***.***>:

> OK from the top of my head I think this is something I have not yet  
> implemented because no one had asked for it.
>
> Specify contrasts at the session level is not yet present here:
> https://github.com/cpp-lln-lab/bidspm/blob/05d92e9ebcf854e42d2cd12db55495479704239c/src/stats/subject_level/specifyContrasts.m#L60-L74
>
> It vaguely relates to: https://github.com/cpp-lln-lab/bidspm/issues/809
>
> Just to be clear the way this will most likely be implemented is to  
> have all runs in single model and then compute contrasts session wise.
>
>
>
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/cpp-lln-lab/bidspm/issues/1007#issuecomment-1531580884
> You are receiving this because you authored the thread.
>
> Message ID: ***@***.***>



Ralf Veit PhD
Institute for Diabetes Research and Metabolic Diseases of the  
Helmholtz Center Munich at the University of Tübingen
Otfried Müller Str. 47
fax: +49-7071-295706
phone: +49-7071-2987703

**Comment by Remi-Gau** [comment]
Yes I think we agree on that. I may be phrasing it poorly.

Now I just need to find an example dataset to test and work on this. As I do I will most likely ask you for feedback to make sure we are on the same page.

**Comment by Remi-Gau** [comment]
Note to self.

Check the bids stats model Zoo or the fitlins repo to they have multisession examples with cross session contrasts.

**Comment by Rageve** [comment]
thanks for all your effort. For example currently, we analyze one  
study with two sessions and each session has two runs.
The participants see in each session pictures with high-calorie sweet,  
high-calorie savory, low-calorie sweet and low-calorie savory content.
We can create contrasts for each regressor and each condition (i.e.  
only high calorie, only sweet ...) and the difference between  
conditions (i.e. high- vs low calorie).
In this study we have two groups, one with verum and one with placebo.  
The subjects will be measured before the treatment (ses-V0) and after  
the treatment (ses-V9).
When we combine all sessions in one first level model, one interesting  
contrast will be the interaction between condition and treatment  
(let's say high- vs low-calorie in ses-V0 versus ses-V9 for example 1  
-1 1 -1 -1 1 -1 1) in the two groups.
The question is which contrast do you define in the first level model  
or in the second level model. The factor group can be only defined in  
a second level model. The factor session and/or condition (and their  
combinations) can be defined in the first or the second level model.
In another study we use insulin or placebo spray in ses-V0 or in  
ses-V9 in counter-balanced order (within subject design). In this case  
it might be better to use a first level model separately for the  
different sessions and use the contrast images based on the assignment  
of the two sessions in the second level model. Hopefully things become  
now more clear.



Zitat von Remi Gau ***@***.***>:

> Yes I think we agree on that. I may be phrasing it poorly.
>
> Now I just need to find an example dataset to test and work on this.  
> As I do I will most likely ask you for feedback to make sure we are  
> on the same page.
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/cpp-lln-lab/bidspm/issues/1007#issuecomment-1531733451
> You are receiving this because you authored the thread.
>
> Message ID: ***@***.***>



Ralf Veit PhD
Institute for Diabetes Research and Metabolic Diseases of the  
Helmholtz Center Munich at the University of Tübingen
Otfried Müller Str. 47
fax: +49-7071-295706
phone: +49-7071-2987703

**Comment by Remi-Gau** [comment]
Wow. Thanks that definitely helps get the idea of the analysis you have in mind.

I have checked and there seems to be no example for such model in the model Zoo repo.

https://github.com/bids-standard/model-zoo/issues/44

So this will the perfect occasion to also add one so that people in your situation have some guidance to follow.

Will be a bit busy in the coming days but I will make the time to work on this.

**Comment by Remi-Gau** [comment]
@Rageve 
Finally took some time this weekend to implement session level analysis.

I tested it on a couple of datasets from openneuro to run some kind of test / restest analysis across sessions.

The scripts are there: https://github.com/cpp-lln-lab/bidspm/tree/main/demos/openneuro

And the example for the  BIDS stats model are here: 

- https://github.com/cpp-lln-lab/bidspm/blob/main/demos/openneuro/models/model-ds000114_desc-testRetestVerbal_smdl.json
- https://github.com/cpp-lln-lab/bidspm/blob/main/demos/openneuro/models/model-ds000224_desc-glasslexical_smdl.json

**Comment by Rageve** [comment]
Hi Remi,

Many thanks for your support. bidspm is increasingly becoming a valuable tool.


Zitat von Remi Gau ***@***.***>:

> @Rageve
> Finally took some time this weekend to implement session level analysis.
>
> I tested it on a couple of datasets from openneuro to run some kind  
> of test / restest analysis across sessions.
>
> The scripts are there:  
> https://github.com/cpp-lln-lab/bidspm/tree/main/demos/openneuro
>
> And the example for the  BIDS stats model are here:
>
> -  
> https://github.com/cpp-lln-lab/bidspm/blob/main/demos/openneuro/models/model-ds000114_desc-testRetestVerbal_smdl.json
> -  
> https://github.com/cpp-lln-lab/bidspm/blob/main/demos/openneuro/models/model-ds000224_desc-glasslexical_smdl.json
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/cpp-lln-lab/bidspm/issues/1007#issuecomment-1667187309
> You are receiving this because you were mentioned.
>
> Message ID: ***@***.***>



Ralf Veit PhD
Institute for Diabetes Research and Metabolic Diseases of the  
Helmholtz Center Munich at the University of Tübingen
Otfried Müller Str. 47
fax: +49-7071-295706
phone: +49-7071-2987703

**Comment by Remi-Gau** [comment]
Setting up those models can be challenging so let me know if you are struggling.

**Comment by Remi-Gau** [comment]
glad it is useful though
