### ISSUE TITLE
Update submodules when running `bidspm update`

### ISSUE THREAD

**Issue by iqrashahzad14** [cpp-lln-lab/bidspm#1027]
Hello, 
I have been using bidspm v3.0 and then I updated by bidspm by typing this in the matlab command line
`bidspm update`.
I wanted to create a roi.
```
bidspm(bids_dir, output_dir, 'subject', ...
    'action', 'create_roi', ...
    'participant_label', {'001'}, ...
    'verbosity', 2, ...
    'roi_atlas', 'glasser', ...
    'roi_name', {'Area_1', 'Area_2'}, ...
    'hemisphere', {'L'}, ...
    'space', {'IXI549Space'})
```

I received an error : "unknown atlas type".

Here is the full log of the error
{
  "GeneratedBy": {
    "name": "bidspm",
    "Version": "v3.0.0",
    "Branch": "HEAD",
    "Commit": "0c530973",
    "Description": "",
    "CodeURL": "https://github.com/cpp-lln-lab/bidspm",
    "DOI": "https://doi.org/10.5281/zenodo.3554331"
  },
  "OS": {
    "name": "macOS",
    "version": "12.6",
    "platform": {
      "name": "MATLAB",
      "version": "9.9.0.1570001 (R2020b) Update 4"
    },
    "spmVersion": "SPM12 - 7771",
    "environmentVariables": {
      "COMMAND_MODE": "unix2003",
      "HOME": "/Users/shahzad",
      "ICU_TIMEZONE_FILES_DIR": "/Applications/MATLAB_R2020b.app/bin/icutzdata",
      "KMP_BLOCKTIME": "1",
      "KMP_HANDLE_SIGNALS": "0",
      "KMP_INIT_AT_FORK": "false",
      "KMP_STACKSIZE": "512k",
      "LANG": "en_US.UTF-8",
      "LC_CTYPE": "UTF-8",
      "LC_MESSAGES": "en_GB",
      "LOGNAME": "shahzad",
      "MATLAB_USE_USERWORK": "",
      "MEMKIND_HEAP_MANAGER": "TBB",
      "MKL_DOMAIN_NUM_THREADS": "",
      "MKL_NUM_THREADS": "",
      "OLDPWD": "/Users/shahzad/Files/fMRI/visTac/fMRI_analysis_GlasserUpdate/code/src",
      "PATH": "/usr/bin:/bin:/usr/sbin:/sbin",
      "PWD": "/Users/shahzad/Files/fMRI/visTac/fMRI_analysis_GlasserUpdate/code/src",
      "SHELL": "/bin/zsh",
      "SHLVL": "0",
      "SSH_AUTH_SOCK": "/private/tmp/com.apple.launchd.L7MH4eoSNX/Listeners",
      "TERM": "dumb",
      "TMPDIR": "/var/folders/_g/60zh19kx5zx8g9tjnj45zlpw0000gp/T/",
      "USER": "shahzad",
      "XPC_FLAGS": "0x0",
      "XPC_SERVICE_NAME": "application.com.mathworks.matlab.1505091.2423124",
      "CFBundleIdentifier": "com.mathworks.matlab",
      "CF_USER_TEXT_ENCODING": "0x1F6:0x0:0x2",
      "KMP_REGISTERED_LIB______": "0x11926f1a8-cafec0ba-libiomp5.dylib"
    }
  },
  "ME": {
    "identifier": "",
    "message": "unknown atlas type",
    "cause": [],
    "stack": [
      {
        "file": "/Users/shahzad/Files/fMRI/visTac/fMRI_analysis_GlasserUpdate/code/lib/bidspm/lib/CPP_ROI/atlas/returnAtlasDir.m",
        "name": "returnAtlasDir",
        "line": 34
      },
      {
        "file": "/Users/shahzad/Files/fMRI/visTac/fMRI_analysis_GlasserUpdate/code/lib/bidspm/lib/CPP_ROI/src/atlas/getLookUpTable.m",
        "name": "getLookUpTable",
        "line": 21
      },
      {
        "file": "/Users/shahzad/Files/fMRI/visTac/fMRI_analysis_GlasserUpdate/code/lib/bidspm/lib/CPP_ROI/src/atlas/getAtlasAndLut.m",
        "name": "getAtlasAndLut",
        "line": 9
      },
      {
        "file": "/Users/shahzad/Files/fMRI/visTac/fMRI_analysis_GlasserUpdate/code/lib/bidspm/lib/CPP_ROI/src/atlas/extractRoiFromAtlas.m",
        "name": "extractRoiFromAtlas",
        "line": 28
      },
      {
        "file": "/Users/shahzad/Files/fMRI/visTac/fMRI_analysis_GlasserUpdate/code/lib/bidspm/src/workflows/roi/bidsCreateROI.m",
        "name": "bidsCreateROI",
        "line": 48
      },
      {
        "file": "/Users/shahzad/Files/fMRI/visTac/fMRI_analysis_GlasserUpdate/code/lib/bidspm/bidspm.m",
        "name": "create_roi",
        "line": 241
      },
      {
        "file": "/Users/shahzad/Files/fMRI/visTac/fMRI_analysis_GlasserUpdate/code/lib/bidspm/bidspm.m",
        "name": "executeAction",
        "line": 139
      },
      {
        "file": "/Users/shahzad/Files/fMRI/visTac/fMRI_analysis_GlasserUpdate/code/lib/bidspm/bidspm.m",
        "name": "bidspm",
        "line": 83
      }
    ],
    "Correction": []
  }
}

**Comment by Remi-Gau** [comment]
hum... 
I think that the submodule for CPP_ROI did not get updated.

from the terminal, can you navigate into the folder for bidspm and type

```bash
git submodule update --init --recursive && git submodule update --recursive
```

**Comment by iqrashahzad14** [comment]
Nice, it works now :) Thanks!

**Comment by Remi-Gau** [comment]
Will add this extra command to the updating script: may save some people the trouble
