### ISSUE TITLE
JSON syntax error - can't find problematic json file

### ISSUE THREAD

**Issue by avanaudenhaege** [cpp-lln-lab/bidspm#1042]
Hello,
I am using bidspm v3.0.0 
I was preprocessing my data with this command working fine, for different tasks : 
```
bidspm(bids_dir, output_dir, 'subject', ...
       'participant_label', subject_label, ...
       'action', 'preprocess', ...
       'task', task_label, ...
       'ignore', {'qa'}, ... 
       'space', {'individual', 'IXI549Space'}, ...
       'fwhm', 6);
```
I got this error when it started the second task of my list : 
```
bidspm - INFO				
JSON syntax error: expected value but found end of text.
 Error MATLAB:json:ExpectedValueAtEnd occurred:
```

I attach the error log file :  
[error_2023-05-30T19-50.log](https://github.com/cpp-lln-lab/bidspm/files/11665572/error_2023-05-30T19-50.log)

I did not change any json file in the middle and I can't identify which json file is referred to in the error. 
Since then, every time I run my preprocessing, it stops with this error.

**Comment by Remi-Gau** [comment]
Can you run the bids validator on your dataset?
My first idea is that one of your JSON file is not "proper" json (most likely forgot a comma somewhere or added an extra one)

To maybe help you try "indexing" the dataset with bids-matlab

```matlab
bids.layout(bids_dir, 'verbose', true)
```

**Comment by avanaudenhaege** [comment]
Thanks, I did not know this indexing command. Indexing returned one warning that I corrected but still I get the same error. 
I couldn't run the online bids validator, runs forever and make my browser crash ...

**Comment by Remi-Gau** [comment]
if you run in verbose mode it should start listing which subjects are being indexed: this way you can start narrowing it down to know which subject may have a faulty JSON.

You can even narrow it down further by modality and session: see the bids matlab documentation.

https://bids-matlab.readthedocs.io/en/latest/layout_query.html#+bids.layout

```matlab
BIDS = bids.layout(bids_dir, ...
                   'use_schema', true, ...
                   'verbose', true, ...
                   'index_derivatives', false, ...
                   'filter', struct('sub', {{'^0[12]'}}, ...
                                    'modality', {{'anat', 'func'}}, ...
                                    'ses', {{'1', '2'}}));
```

**Comment by Remi-Gau** [comment]
also if you push your data on GIN I can have a quick look... 😜

**Comment by avanaudenhaege** [comment]
I installed bids validator. I just have one critical error : 
`	1: [ERR] A stimulus file was declared but not found in the dataset. (code: 52 - STIMULUS_FILE_MISSING)
		./sub-05/ses-01/func/sub-05_ses-01_task-MVPAAud_run-01_events.tsv
			@ line: 2 character: 3
			Evidence: S1fi.wav
		./sub-05/ses-01/func/sub-05_ses-01_task-MVPAAud_run-01_events.tsv
			@ line: 3 character: 3
			Evidence: S2pa.wav
		./sub-05/ses-01/func/sub-05_ses-01_task-MVPAAud_run-01_events.tsv
			@ line: 5 character: 3
			Evidence: S3le.wav
		./sub-05/ses-01/func/sub-05_ses-01_task-MVPAAud_run-01_events.tsv
			@ line: 7 character: 3
			Evidence: S3fi.wav
		./sub-05/ses-01/func/sub-05_ses-01_task-MVPAAud_run-01_events.tsv
			@ line: 9 character: 3
			Evidence: S1fa.wav
		./sub-05/ses-01/func/sub-05_ses-01_task-MVPAAud_run-01_events.tsv
			@ line: 11 character: 3
			Evidence: S2pe.wav
		./sub-05/ses-01/func/sub-05_ses-01_task-MVPAAud_run-01_events.tsv
			@ line: 13 character: 3
			Evidence: S2le.wav
		./sub-05/ses-01/func/sub-05_ses-01_task-MVPAAud_run-01_events.tsv
			@ line: 15 character: 3
			Evidence: S1le.wav
		./sub-05/ses-01/func/sub-05_ses-01_task-MVPAAud_run-01_events.tsv
			@ line: 17 character: 3
			Evidence: S1la.wav
		./sub-05/ses-01/func/sub-05_ses-01_task-MVPAAud_run-01_events.tsv
			@ line: 19 character: 3
			Evidence: S1li.wav
		... and 9181 more files having this issue (Use --verbose to see them all).`

Nothing about an inappropriate json file.

**Comment by avanaudenhaege** [comment]
I will try to push my data on GIN this afternoon. Thanks :)

**Comment by Remi-Gau** [comment]
closing for now

but reopen if you still have problems
