### ISSUE TITLE
[BUG] Rename does not happen if re-running a step without deleting previous resutls

### ISSUE THREAD

**Issue by marcobarilari** [cpp-lln-lab/bidspm#1045]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

That the spm like named files will be re named even if the file with the target name is there already from a previous run of the same process.

### Current Behavior

it does not rename the files and keeps a copy with spm name (new output) and bids name (previous output)

### Environment

```markdown
- OS:
- Matlab:
- SPM:
```

### Branch

```markdown
- branch:
- version:
```

### Anything else?

Not sure if this is a bug or a feature .... bu I think people might get confused and when re-running stuff they might look for the bids like name files 

Tagging @iqrashahzad14 that might be interested

**Comment by marcobarilari** [comment]
also from FAQ

> What happens if we run same code twice?[](https://bidspm.readthedocs.io/en/latest/FAQ.html#general-what-happens-if-we-run-same-code-twice)
In the vast majority of cases, if you have not touched anything to your options, you will overwrite the output.

**Comment by Remi-Gau** [comment]
hahaha
good catch
let's try to make the code consistent with the doc, indeed

**Comment by iqrashahzad14** [comment]
Yes, indeed we were thinking that renaming is the default option. Would be nice to get that :)

**Comment by Remi-Gau** [comment]
OK this overwriting should now be the new default.

I decided to not allow this to change this via the "CLI" like this

```matlab
bidspm(bids_dir, output_dir, 'subject', ...
        'action', 'preprocess', ...
        'overwrite', false)
```

But via the options because I believe users won't need that too often.

```matlab
opt.rename.overwrite = false;
bidspm(bids_dir, output_dir, 'subject', ...
        'action', 'preprocess', ...
        'options', opt)
```

**Comment by marcobarilari** [comment]
Makes actually sense, thank you!
