### ISSUE TITLE
[BUG] choosing subjects with label "001", indexes both sub-001 and sub-pil001

### ISSUE THREAD

**Issue by iqrashahzad14** [cpp-lln-lab/bidspm#1095]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating system

- [ ] Linux
- [X] Mac
- [ ] Windows

### Operating system version

- Mac OS Version 12 "monterey"

### SPM 12 version

- [X] 7771
- [ ] 7487
- [ ] 7219

### Platform

- [X] MATLAB
- [ ] Octave

### Platform version

- MATLAB 2020b

### bidspm version

v3.1.0

### Expected Behavior

Hello, I was trying preprocessing with the latest version of bidspm. 

taskList = {'visualLocalizer2','tactileLocalizer2','mtMstLocalizer'};

    taskName = 'visualLocalizer2;
    bidspm(bids_dir, output_dir, 'subject', ... 
            'action', 'preprocess', ...
            'participant_label', {'001'}, ...
            'space', {'IXI549Space'}, ...
            'fwhm', 6,...
            'task', {taskName})

I expect it to read only sub-001. But it indexes both sub-001 and sub-pil001. Basically all subjects with "001".

And then it, it throws n error that it cannot read the repetition time for this task and subject, which is obvious because this task and subject doesn't exist. 

How can I prevent it from reading both the subjects?

### Current Behavior & Error message

```matlab
% copy the error you got below
% before the three backticks (```)

{
  "GeneratedBy": {
    "name": "bidspm",
    "Version": "v3.1.0",
    "Branch": "HEAD",
    "Commit": "7a40bb27",
    "Description": "",
    "CodeURL": "https://github.com/cpp-lln-lab/bidspm",
    "DOI": "https://doi.org/10.5281/zenodo.3554331"
  },
  "OS": {
    "name": "macOS",
    "version": "12.6",
    "platform": {
      "name": "MATLAB",
      "version": "9.9.0.1570001 (R2020b) Update 4"
    },
    "spmVersion": "SPM12 - 7771",
    "environmentVariables": {
      "COMMAND_MODE": "unix2003",
      "HOME": "/Users/shahzad",
      "ICU_TIMEZONE_FILES_DIR": "/Applications/MATLAB_R2020b.app/bin/icutzdata",
      "KMP_BLOCKTIME": "1",
      "KMP_HANDLE_SIGNALS": "0",
      "KMP_INIT_AT_FORK": "false",
      "KMP_STACKSIZE": "512k",
      "LANG": "en_US.UTF-8",
      "LC_CTYPE": "UTF-8",
      "LC_MESSAGES": "en_GB",
      "LOGNAME": "shahzad",
      "MATLAB_USE_USERWORK": "",
      "MEMKIND_HEAP_MANAGER": "TBB",
      "MKL_DOMAIN_NUM_THREADS": "",
      "MKL_NUM_THREADS": "",
      "OLDPWD": "/Users/shahzad/Files/fMRI/visTac/fMRI_analysis_GlasserUpdate/code/src",
      "PATH": "/usr/bin:/bin:/usr/sbin:/sbin",
      "PWD": "/Users/shahzad/Files/fMRI/visTac/fMRI_analysis_GlasserUpdate/code/src",
      "SHELL": "/bin/zsh",
      "SHLVL": "0",
      "SSH_AUTH_SOCK": "/private/tmp/com.apple.launchd.DqHsAgEqhl/Listeners",
      "TERM": "dumb",
      "TMPDIR": "/var/folders/_g/60zh19kx5zx8g9tjnj45zlpw0000gp/T/",
      "USER": "shahzad",
      "XPC_FLAGS": "0x0",
      "XPC_SERVICE_NAME": "application.com.mathworks.matlab.1505091.2423124",
      "CFBundleIdentifier": "com.mathworks.matlab",
      "CF_USER_TEXT_ENCODING": "0x1F6:0x0:0x2",
      "KMP_REGISTERED_LIB______": "0x11031a1a8-cafe82bf-libiomp5.dylib"
    }
  },
  "ME": {
    "identifier": "getAndCheckRepetitionTime:noRepetitionTimeFound",
    "message": "\n[15:20:05] bidspm - ERROR\t\t\t\tgetAndCheckRepetitionTime\nNo repetition time found for filter:\n\n\t- desc: {}\n\t- extension: {.nii.*}\n\t- modality: {func}\n\t- prefix: {}\n\t- space: {}\n\t- sub: {^pil001$}\n\t- suffix: {bold}\n\t- task: {visualLocalizer2}\n\t- target: {RepetitionTime}\\n",
    "cause": [],
    "stack": [
      {
        "file": "/Users/shahzad/Files/fMRI/visTac/fMRI_analysis_GlasserUpdate/code/lib/bidspm/src/messages/errorHandling.m",
        "name": "errorHandling",
        "line": 57
      },
      {
        "file": "/Users/shahzad/Files/fMRI/visTac/fMRI_analysis_GlasserUpdate/code/lib/bidspm/src/messages/logger.m",
        "name": "logger",
        "line": 70
      },
      {
        "file": "/Users/shahzad/Files/fMRI/visTac/fMRI_analysis_GlasserUpdate/code/lib/bidspm/src/bids/getAndCheckRepetitionTime.m",
        "name": "getAndCheckRepetitionTime",
        "line": 62
      },
      {
        "file": "/Users/shahzad/Files/fMRI/visTac/fMRI_analysis_GlasserUpdate/code/lib/bidspm/src/batches/preproc/setBatchSTC.m",
        "name": "setBatchSTC",
        "line": 53
      },
      {
        "file": "/Users/shahzad/Files/fMRI/visTac/fMRI_analysis_GlasserUpdate/code/lib/bidspm/src/workflows/preproc/bidsSTC.m",
        "name": "bidsSTC",
        "line": 47
      },
      {
        "file": "/Users/shahzad/Files/fMRI/visTac/fMRI_analysis_GlasserUpdate/code/lib/bidspm/bidspm.m",
        "name": "preprocess",
        "line": 288
      },
      {
        "file": "/Users/shahzad/Files/fMRI/visTac/fMRI_analysis_GlasserUpdate/code/lib/bidspm/bidspm.m",
        "name": "executeAction",
        "line": 156
      },
      {
        "file": "/Users/shahzad/Files/fMRI/visTac/fMRI_analysis_GlasserUpdate/code/lib/bidspm/bidspm.m",
        "name": "bidspm",
        "line": 83
      }
    ],
    "Correction": []
  }
}


```

**Comment by Remi-Gau** [comment]
Try using a regex instead of just the subject number.

So '^011$' and not just '001'.

But avoiding the crash could be a good thing so I should probably handle that error better.

**Comment by iqrashahzad14** [comment]
Thanks ! just to be clear is it '^011$' or '^001$' for 'sub-001'? (I mean the extra one is a typo , right?)

**Comment by iqrashahzad14** [comment]
Tried the following:
taskName = 'visualLocalizer2';
    bidspm(bids_dir, output_dir, 'subject', ... 
            'action', 'preprocess', ...
            'participant_label', {'^001$'}, ...
            'space', {'IXI549Space'}, ...
            'fwhm', 6,...
            'task', {taskName})
            
Bidspm was still looking for both sub-001 and sub-pil001

I got the following error:

"""{
  "GeneratedBy": {
    "name": "bidspm",
    "Version": "v3.1.0",
    "Branch": "HEAD",
    "Commit": "7a40bb27",
    "Description": "",
    "CodeURL": "https://github.com/cpp-lln-lab/bidspm",
    "DOI": "https://doi.org/10.5281/zenodo.3554331"
  },
  "OS": {
    "name": "macOS",
    "version": "12.6",
    "platform": {
      "name": "MATLAB",
      "version": "9.9.0.1570001 (R2020b) Update 4"
    },
    "spmVersion": "SPM12 - 7771",
    "environmentVariables": {
      "COMMAND_MODE": "unix2003",
      "HOME": "/Users/shahzad",
      "ICU_TIMEZONE_FILES_DIR": "/Applications/MATLAB_R2020b.app/bin/icutzdata",
      "KMP_BLOCKTIME": "1",
      "KMP_HANDLE_SIGNALS": "0",
      "KMP_INIT_AT_FORK": "false",
      "KMP_STACKSIZE": "512k",
      "LANG": "en_US.UTF-8",
      "LC_CTYPE": "UTF-8",
      "LC_MESSAGES": "en_GB",
      "LOGNAME": "shahzad",
      "MATLAB_USE_USERWORK": "",
      "MEMKIND_HEAP_MANAGER": "TBB",
      "MKL_DOMAIN_NUM_THREADS": "",
      "MKL_NUM_THREADS": "",
      "OLDPWD": "/Users/shahzad/Files/fMRI/visTac/fMRI_analysis_GlasserUpdate/code/src",
      "PATH": "/usr/bin:/bin:/usr/sbin:/sbin",
      "PWD": "/Users/shahzad/Files/fMRI/visTac/fMRI_analysis_GlasserUpdate/code/src",
      "SHELL": "/bin/zsh",
      "SHLVL": "0",
      "SPM_NUM_THREADS": "1",
      "SSH_AUTH_SOCK": "/private/tmp/com.apple.launchd.DqHsAgEqhl/Listeners",
      "TERM": "dumb",
      "TMPDIR": "/var/folders/_g/60zh19kx5zx8g9tjnj45zlpw0000gp/T/",
      "USER": "shahzad",
      "XPC_FLAGS": "0x0",
      "XPC_SERVICE_NAME": "application.com.mathworks.matlab.1505091.2423124",
      "CFBundleIdentifier": "com.mathworks.matlab",
      "CF_USER_TEXT_ENCODING": "0x1F6:0x0:0x2",
      "KMP_REGISTERED_LIB______": "0x11031a1a8-cafe82bf-libiomp5.dylib"
    }
  },
  "ME": {
    "identifier": "bidsQApreproc:wrongNumberOFFiles",
    "message": "\n[15:59:32] bidspm - ERROR\t\t\t\tbidsQApreproc\ntoo many files found:\n\n\t- \n\n\nfor filter:\\n",
    "cause": [],
    "stack": [
      {
        "file": "/Users/shahzad/Files/fMRI/visTac/fMRI_analysis_GlasserUpdate/code/lib/bidspm/src/messages/errorHandling.m",
        "name": "errorHandling",
        "line": 57
      },
      {
        "file": "/Users/shahzad/Files/fMRI/visTac/fMRI_analysis_GlasserUpdate/code/lib/bidspm/src/messages/logger.m",
        "name": "logger",
        "line": 70
      },
      {
        "file": "/Users/shahzad/Files/fMRI/visTac/fMRI_analysis_GlasserUpdate/code/lib/bidspm/src/workflows/bidsQApreproc.m",
        "name": "bidsQApreproc",
        "line": 118
      },
      {
        "file": "/Users/shahzad/Files/fMRI/visTac/fMRI_analysis_GlasserUpdate/code/lib/bidspm/src/workflows/preproc/bidsSpatialPrepro.m",
        "name": "bidsSpatialPrepro",
        "line": 137
      },
      {
        "file": "/Users/shahzad/Files/fMRI/visTac/fMRI_analysis_GlasserUpdate/code/lib/bidspm/bidspm.m",
        "name": "preprocess",
        "line": 290
      },
      {
        "file": "/Users/shahzad/Files/fMRI/visTac/fMRI_analysis_GlasserUpdate/code/lib/bidspm/bidspm.m",
        "name": "executeAction",
        "line": 156
      },
      {
        "file": "/Users/shahzad/Files/fMRI/visTac/fMRI_analysis_GlasserUpdate/code/lib/bidspm/bidspm.m",
        "name": "bidspm",
        "line": 83
      }
    ],
    "Correction": []
  }
}
"""

[error_2023-07-28T15-59.log](https://github.com/cpp-lln-lab/bidspm/files/12195355/error_2023-07-28T15-59.log)

**Comment by Remi-Gau** [comment]
The error seems different, no?
It was failing on slice time correction and now on pre processing qa.

**Comment by Remi-Gau** [comment]
Will close for now but reopen if you get the same error or open another issue if you get another one.
