### ISSUE TITLE
[BUG] When running `bidspm update` from Matlab, submod(s) not updated

### ISSUE THREAD

**Issue by marcobarilari** [cpp-lln-lab/bidspm#1200]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating system

- [X] Linux
- [ ] Mac
- [ ] Windows

### Operating system version

- Linux Ubuntu 22.04 "jammy jellyfish"

### SPM 12 version

- [X] 7771
- [ ] 7487
- [ ] 7219

### Platform

- [X] MATLAB
- [ ] Octave

### Platform version

- MATLAB 2018a

### bidspm version

v3.1.0

### bidspm branch / commit number

actual version is 3.1.0dev

branch =

    'main'

commit =

    '97e63840'

### Expected Behavior

To update my software

### Current Behavior & Error message

I wanted to update bidspm to latest version from the matlab command line (previous version was 3.0.0), though I have the impression that at least 1 submod is not updated as well (`spm_2_bids`) since I get an error that a function (`guess_modality`) is not known.  

### Anything else?

Did not check if the version of the other submods are those that 3.1.0dev is tracking

**Comment by Remi-Gau** [comment]
I tried it from the commit you were at and things seemed to wrok

```matlab
>> bidspm update

[09:11:33] bidspm - INFO				
bidspm already initialized
bash tools/update.sh
you are on branch main
From https://github.com/cpp-lln-lab/bidspm
 * [new branch]        main       -> tmp/main
 * [new branch]        paper      -> tmp/paper
 * [new branch]        v0.1.1     -> tmp/v0.1.1
From https://github.com/cpp-lln-lab/bidspm
 * branch              main       -> FETCH_HEAD
Updating 97e63840..967f16a4
Fast-forward
 .pre-commit-config.yaml | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
ans =
     0
     
>> which guess_modality
/home/remi/github/cpp-lln-lab/bidspm/lib/spm_2_bids/src/utils/guess_modality.m
```


Also until a few minutes ago `97e63840` was already the latest commit (now I just merged a maintenance PR). So it should not have changed anything.

**Comment by marcobarilari** [comment]
Hey, thank for checking. Let me try to reproduce it again as well. The starting point is save on github and I can point you to that repo later if necessary.

**Comment by marcobarilari** [comment]
I noticed one thing, the commit I provided when I opened this issue wasn't the actual commit from where I updated bidspm

**Comment by Remi-Gau** [comment]
ha yes then it makes sense because this is a bug that was fixed here: https://github.com/cpp-lln-lab/bidspm/issues/1027

so between 3.0 and 3.1 therefore it would fail when updating from 3.0

**Comment by marcobarilari** [comment]
awesome, apologies for not having checked issues and PR thoroughly

**Comment by Remi-Gau** [comment]
no worries
i had forgotten about it entirely

**Comment by Remi-Gau** [comment]
it was not even in the changelog so defo harder to find
