### ISSUE TITLE
[BUG] bidsCopyInputFolder doesn't follow output directory

### ISSUE THREAD

**Issue by JacMatu** [cpp-lln-lab/bidspm#1205]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating system

- [ ] Linux
- [X] Mac
- [ ] Windows

### SPM 12 version

- [ ] 7771
- [ ] 7487
- [X] 7219

### Platform

- [X] MATLAB
- [ ] Octave

### Platform version

- MATLAB 2019a
- Octave 4.2.2

### bidspm version

v3.1.0

### Expected Behavior

I'm running 
`bidsCopyInputFolder(opt,'unzip', true)`
with intention to copy and unzip data from `raw` to `derivatives/bidspm-preproc` for further processing (generating T1 maps)

dirs are set up like this: 

```matlab
opt.dir.input = fullfile(root_dir, 'inputs', 'raw');
opt.dir.derivatives= fullfile(root_dir,'outputs','derivatives');
opt.dir.output = fullfile(root_dir,'outputs','derivatives', 'bidspm-preproc');
``` 

with my expectancy to copy and unzip stuffs from `opt.dir.input` to `opt.dir.output`, e.g. to have an unzipped files in `derivatives/bidspm-preproc`

### Current Behavior & Error message

Instead, `bidsCopyInputFolder` creates a new dir in `derivatives`, called simply `bidspm`, ignoring my target output to store unzipped data. 

### Anything else?

can it be caused by 
```
    bids.copy_to_derivative(BIDS, ...
                            'pipeline_name', pipeline_name, ...
                            'out_path', fullfile(opt.dir.output, '..'), ...
                            'filter', filter, ...
                            'unzip', unzip, ...
                            'force', force, ...
                            'skip_dep', skip_dependencies, ...
                            'use_schema', use_schema, ...
                            'verbose', opt.verbosity > 0, ...
                            'tolerant', TOLERANT);
```
I see  'out_path', fullfile(opt.dir.output, '..') to skip one dir above the output. 
When I changed it to `'out_path', opt.dir.output` files were copied and unzipped to `derivatives/bidspm-preproc/bidspm'

This never happened when I used bidspm workflows like preproc (that also include copying and unzipping data), just when I want to use that function in isolation to prepare for things that are not covered by main workflows (T1 map generation, data upsampling, denoising with `presurfer`, etc.)

**Comment by Remi-Gau** [comment]
checking this one as part of #1275 that should fix this, but I recommend using `bidspm(..., 'action', 'copy')` instead of of the lower level `bidsCopyInputFolder`: makes your life easier with all the input and output dir.

input data
```
demos/MoAE/inputs/raw
├── CHANGES
├── dataset_description.json
├── participants.tsv
├── README
├── sub-01
│   ├── anat
│   │   └── sub-01_T1w.nii
│   └── func
│       ├── sub-01_task-auditory_bold.nii
│       └── sub-01_task-auditory_events.tsv
└── task-auditory_bold.json
```

script
```matlab
  inputPath = fullfile(getMoaeDir(), 'inputs', 'raw');

  outputPath = tempName();

  bidspm(inputPath, outputPath, 'subject', ...
         'action', 'copy', ...
         'anat_only', true, ...
         'verbosity', 3);

  BIDS = bids.layout(fullfile(outputPath, 'derivatives', 'bidspm-preproc'), ...
                     'verbose', false, ...
                     'use_schema', false);

  assertEqual(numel(bids.query(BIDS, 'data')), 1);
```

output
```
/tmp/tp25442fd5_42bf_4d7d_90d4_3a4353f87526/
└── derivatives
    ├── bidspm-preproc
    │   ├── CHANGES
    │   ├── dataset_description.json
    │   ├── LICENSE
    │   ├── README.md
    │   └── sub-01
    │       └── anat
    │           └── sub-01_T1w.nii
    └── options
        └── options_2024-07-09T22-52.json
```
