### ISSUE TITLE
Definition file for apptainer

### ISSUE THREAD

**Issue by monique2208** [cpp-lln-lab/bidspm#1240]
We use apptainer. I tried to directly convert the docker image, but this does not work because of the different ways docker and apptainer handle the home directory. 

The issue is that home is not available when apptainer builds the container. The octave savepath function tries to write the new paths into the octaverc file in home by default, so it ends in the container root. But this file is not read again when the container runs. I converted the docker file into a definition file, where I specify that the new paths should be saved in a global octaverc file, so that home is not required. 

I add it here if anyone is interested. I have done limited testing but I have not had issues so far. 

<details>
<summary>apptainer/singularity definition file</summary>
 
```
BootStrap: docker
From: bids/base_validator

%post
    apt-get -qq update
    DEBIAN_FRONTEND=noninteractive apt-get --yes --quiet install \
        build-essential \
        software-properties-common \
        apt-utils \
        ca-certificates \
        git \
        curl \
        python3 \
        python3-pip \
        fonts-freefont-otf \
        ghostscript \
        gnuplot-x11 \
        libcurl4-gnutls-dev \
        octave \
        liboctave-dev \
        octave-common \
        octave-io \
        octave-image \
        octave-signal \
        octave-statistics && \
    apt-get clean && \
    rm -rf \
        /tmp/hsperfdata* \
        /var/*/apt/*/partial \
        /var/lib/apt/lists/* \
        /var/log/apt/term*
    
    mkdir /opt/spm12
    curl -fsSL --retry 5 https://github.com/spm/spm12/archive/r7771.tar.gz | tar -xzC /opt/spm12 --strip-components 1 
    curl -fsSL --retry 5 https://raw.githubusercontent.com/spm/spm-octave/main/spm12_r7771.patch | patch -p0
    make -C /opt/spm12/src PLATFORM=octave distclean
    make -C /opt/spm12/src PLATFORM=octave
    make -C /opt/spm12/src PLATFORM=octave install
    ln -s /opt/spm12/bin/spm12-octave /usr/local/bin/spm12

    mkdir /opt/bidspm
    git clone --recurse-submodules https://github.com/cpp-lln-lab/bidspm.git /opt/bidspm
    pip install --no-cache-dir --upgrade pip && \
    pip3 --no-cache-dir install /opt/bidspm && \
    octave --no-gui --eval "addpath('/opt/spm12/'); savepath ('/usr/share/octave/site/m/startup/octaverc');" && \
    octave --no-gui --eval "addpath('/opt/bidspm/'); savepath('/usr/share/octave/site/m/startup/octaverc'); bidspm(); path"

%runscript
    bidspm "$@"

%help
    BIDSpm container
```
 
</details>

**Comment by Remi-Gau** [comment]
Will move this into a PR to be added to the code base: easier to find for others

**Comment by Remi-Gau** [comment]
@all-contributors please add @monique2208 for code

**Comment by Remi-Gau** [comment]
@monique2208 I may try to actually incorporate this change in the dockerfile recipe directly so that there is only a single container definition for docker and apptainer (easier for maintenance)

if you see that the image you build when pulling from dockerhub with apptainer is giving trouble again, reopen the issue.
