### ISSUE TITLE
functionalQA error using in spmup_volumecorr

### ISSUE THREAD

**Issue by CerenB** [cpp-lln-lab/bidspm#174]
Hmm... What would be the reason for the below issue?
I used `functionalQA` yesterday, it was OK. And today with a new subject, I've received below error:

```
FOR TASK: RhythmFT
WILL WORK ON SUBJECTS
    '001'

 FUNCTIONAL: QUALITY CONTROL

 PROCESSING GROUP: SUBJECT No.: 1 SUBJECT ID : 001 
tSNR - reading data ..
tSNR - computing metrics ..
tSNR - making voxel wise tSNR image ..
tSNR - checking linearlity ..
Defaults settings have been modified by file(s):
  /Users/battal/Cerens_files/fMRI/Processed/RhythmCateg/Pilots/RhythmFT/code/rhythmFT_fMRI_analysis/src/../lib/CPP_BIDS_SPM_pipeline/src/defaults/spm_my_defaults.m
  /Users/battal/Cerens_files/fMRI/Processed/RhythmCateg/Pilots/RhythmBlock/code/rhythmBlock_fMRI_analysis/src/../lib/CPP_BIDS_SPM_pipeline/src/defaults/spm_my_defaults.m
  /Users/battal/Cerens_files/fMRI/Processed/RhythmCateg/Pilots/RhythmBlock/code/rhythmBlock_fMRI_analysis/src/../spm_my_defaults.m
Modified fields: ui mat stats realign 
processing data /Users/battal/Cerens_files/fMRI/Processed/RhythmCateg/Pilots/RhythmFT/derivatives/cpp_spm/sub-001/ses-001/func/uasub-001_ses-001_task-RhythmFT_run-001_bold.nii 
Defaults settings have been modified by file(s):
  /Users/battal/Cerens_files/fMRI/Processed/RhythmCateg/Pilots/RhythmFT/code/rhythmFT_fMRI_analysis/src/../lib/CPP_BIDS_SPM_pipeline/src/defaults/spm_my_defaults.m
  /Users/battal/Cerens_files/fMRI/Processed/RhythmCateg/Pilots/RhythmBlock/code/rhythmBlock_fMRI_analysis/src/../lib/CPP_BIDS_SPM_pipeline/src/defaults/spm_my_defaults.m
  /Users/battal/Cerens_files/fMRI/Processed/RhythmCateg/Pilots/RhythmBlock/code/rhythmBlock_fMRI_analysis/src/../spm_my_defaults.m
Modified fields: ui mat stats realign 
getting displacement ... 
computing globals for outliers ... 
making the time series movie ...
realign QA done
1st level QA done
reading and thresholding masks ... 
getting frame wise displacement
getting WM and CSF traces
getting volume correlations
Error using spmup_volumecorr (line 23)
you do not have stats toolbox to perform this operation, sorry

Error in spmup_timeseriesplot (line 231)
            [r_course(1, :), r_course(2, :)] = spmup_volumecorr(fmridata);

Error in functionalQA (line 113)
          spmup_timeseriesplot(funcImage, TPMs(1, :), TPMs(2, :), TPMs(3, :), ...

Error in RhythmFT_run (line 34)
 functionalQA(opt);
```

**Comment by Remi-Gau** [comment]
Ha yes : `spmup_timeseriesplot` is the `spmup` function that does the carpet plot. And that's new.

For the moment, you can just comment out line 113 in `functionalQA`

Maybe the dirty hack is to add a flag `opt.QA.useCarpetPlot` and to have it as `false` by default: but I don't like the idea to have too many flags in options. This will keep growing for sure...

Cleaner way, to do it (which I should probably implement) is to check that if we are running matlab with the required toolbox and then continue otherwise (lack of toolbox or Octave) we skip that step.

**Comment by CerenB** [comment]
It has all the images at the time of crash. The Last image is: `spm_2020Nov10_011.png`

**Comment by Remi-Gau** [comment]
Was that a reply to this comment?
https://github.com/cpp-lln-lab/CPP_SPM/issues/113#issuecomment-725221370

**Comment by CerenB** [comment]
ouch! YES! shall I delete and re-post it there?

**Comment by Remi-Gau** [comment]
For later: try to test if the stats toolbox is present and only run `spmup_volumecorr` if that's the case.

https://fr.mathworks.com/help/matlab/ref/license.html

**Comment by CerenB** [comment]
Is `spmup_volumecorr` a new function that was not used in `cpp-spm` repo couple of days ago? Because couple of days ago functionalQA was working in my laptop. Though when I look at where it complains, it's in stat func, that when I search in my laptop, I have that function.

**Comment by Remi-Gau** [comment]
spmup_timeseriesplot
spmup_timeseriesplot

> Is `spmup_volumecorr` a new function that was not used in `cpp-spm` repo couple of days ago? Because couple of days ago functionalQA was working in my laptop. 

yes this is "new".

Added in the PR #168 

See this commit: https://github.com/cpp-lln-lab/CPP_SPM/pull/168/commits/7d0972fc760a2b746a68b7dc123e75312a337c3b

`spmup_timeseriesplot` creates the carpet plots (a la MRIQC) and calls `spmup_volumecorr`.

**Comment by Remi-Gau** [comment]
>Though when I look at where it complains, it's in stat func, that when I search in my laptop, I have that function.

So I checked `spmup_volumecorr` and here is the line that throws this error.

```
if exist('nansum','file') ~= 2
    error('you do not have stats toolbox to perform this operation, sorry')
end
```

This is a VERY weird way to check if a toolbox is present. #understatement

What does `exist('nansum','file')` or `which nansum` give you?

This needs fixing at the `spmup` level. Will raise an issue there.

**Comment by CerenB** [comment]
```
exist('nansum','file') 

ans =

     2
```

:D so I'm a bit confused here.

**Comment by Remi-Gau** [comment]
What
...
The
...
Hell ?

**Comment by Remi-Gau** [comment]
Let's leave this one open for now to remind us of the horrible hack I used in #181 to "fix this"

**Comment by CerenB** [comment]
it's a bit weird thing but:
```
exist('nansum','file') == 2

ans =

  logical

   0
```

however, 
```
exist('nansum.m','file') == 2

ans =

  logical

   1
```

**Comment by Remi-Gau** [comment]
Huh????? 
Let me fetch a tanto and commit seppuku...
