### ISSUE TITLE
Big size (up to 3GB) fro the  `*bold_qa.json` output from `functionalQA`

### ISSUE THREAD

**Issue by marcobarilari** [cpp-lln-lab/bidspm#195]
## Describe your problem in detail

The json file output `*bold_qa.json` per run from `functionalQA()` is very heavy. Might worth checking what's inside and make sure that huge data are not there.

## Describe what outcome you expected 

A light file that does not kill my HD.

## Describe what you got instead

A file that weights like all the episodes of LOST + Extras BlueRay quality

**Comment by Remi-Gau** [comment]
Well... Well... Well... The minute you decide to make things more organized, your lab mates decide to go for facetious "bug report". 

Well played young man. Well played.

**Comment by Remi-Gau** [comment]
From #208 

by @marcobarilari 

> I have opened the JSON file and the huge entry there is related to jsonFile.tSNR.Background_raw. I guess that just removing this one from the struct that is been saved will do.
