### ISSUE TITLE
functional QA report seems to be mixing up data from different runs

### ISSUE THREAD

**Issue by Remi-Gau** [cpp-lln-lab/bidspm#209]
## Describe your problem in detail

The figure outputs from the functional QA seems to plot for earlier runs for some graphs. 

## Describe what outcome you expected 

Graphs where all variables have the same number of time points for all the time series.

## Describe what you got instead

On the voxplot figure 2 below even though the time series has 200 time points the framewise displacement graph I only get 140 time points and they look suspiciously like the ones from run 1.

### Figure example

![voxplot_001](https://user-images.githubusercontent.com/6961185/100539218-3774f780-3235-11eb-9e5c-6342f81fde74.png)
![voxplot_002](https://user-images.githubusercontent.com/6961185/100539219-39d75180-3235-11eb-8d69-600a14bccc19.png)

**Comment by Remi-Gau** [comment]
@marcobarilari 

Can you confirm this one on your latest run?

**Comment by marcobarilari** [comment]
yes, I confirm that across the six runs the FD plot does not change

**Comment by Remi-Gau** [comment]
Could not reproduce with the demo data (moving to be fixed on later version)
