### ISSUE TITLE
[ENH] rename output figure from functionalQA

### ISSUE THREAD

**Issue by Remi-Gau** [cpp-lln-lab/bidspm#211]
They are currenlty called `voxplot_*.png` and stored in the `func` folder. 

Not the most helpful especially for the filename.

**Comment by CerenB** [comment]
would you consider having `funcQA` results in a subfolder of `func` folder?

**Comment by Remi-Gau** [comment]
I am tempting to indeed move all the "figures" into a common folder.

Either in:
- `sub-subjectLabel/figures` where we are already putting the output figures of the preprocessing
Or in:
- `sub-subjectLabel/ses-sesLable/func/figures` where we would put the output figures of the preprocessing and QA of that session.

I would tend to prefer the first option (fewer bested folders) as long as the filenames make it clear what the file is about. 

What do you think?

**Comment by CerenB** [comment]
as you wish. 
And the QA results would b in func folder, only the figures would move there if I understood you right?

**Comment by marcobarilari** [comment]
agree with @Remi-Gau ,`sub-subjectLabel/figures( /taskName ? )` would do it

**Comment by Remi-Gau** [comment]
> as you wish.
> And the QA results would b in func folder, only the figures would move there if I understood you right?

yes I would keep the funcQA output in the func folder and would only move the figures.
