### ISSUE TITLE
Surface result display

### ISSUE THREAD

**Issue by marcobarilari** [cpp-lln-lab/bidspm#344]
You think / need this code to do **display the results on the brain surface**.

That means that we can improve the code or the documentation.

Tell us more about it below.

Maybe worth to consider the [conn](https://web.conn-toolbox.org/) toolbox (from Olivier suggestion)

**Comment by Remi-Gau** [comment]
I would not mind but I have to admit I am not super enthusiastic into looking into this but if you want to go for a deep dive on that front: be my guest.

**Comment by marcobarilari** [comment]
Yes I will just to be sure whether it is worth it. It is on my to-do since a while

**Comment by Remi-Gau** [comment]
other option
https://github.com/spunt/bspmview

**Comment by Remi-Gau** [comment]
don't think I will have the time to implement this
