### ISSUE TITLE
[ENH]: add option for normalized anat resolution

### ISSUE THREAD

**Issue by marcobarilari** [cpp-lln-lab/bidspm#505]
### Is there an existing issue for this?

- [X] I have searched the existing issues (I lied)

**Comment by Remi-Gau** [comment]
@marcobarilari 
do you remember what we meant in this issue?

**Comment by marcobarilari** [comment]
I have no freaking idea .... probably a reminder to write meaningful text within issues?

**Comment by Remi-Gau** [comment]
indeed

will close this then
