### ISSUE TITLE
add easy checkpoint in pipeline so it does not rerun everything

### ISSUE THREAD

**Issue by Remi-Gau** [cpp-lln-lab/bidspm#65]
for example there is no need to run the segmentation if you are only changing the functional analysis:
- this could be important to save time on the cluster if you hit the wall time
- check notes from the CECI on checkpointing

**Comment by Remi-Gau** [comment]
Another way to do this is to have the analysis of the anat and segmentation being put in a separate derivatives sub-dataset and have other workflows (like spatial preprocessing) being able to grab this data.

**Comment by marcobarilari** [comment]
I add here a discussion with Christoph Philips regarding not re-copy/re-running analysis if the same anat image is in common b/w multiple tasks:

> Effectively one single version of the subject anat image would be ideal -> saves time and processing, moreover one subject should have a single anat processed only once.
> 
> I see a potential pitfall here though, say that:
> 1/ you copy anat and func data A in the derivative folder
> 2/ do the spatial processing as usual, estimating the subject-to-MNI deformation
> 3/ you copy func data B
> 4/ when coregistering func data B and anat, you move the latter (anat-on-func instead of func-on-anat), 
> then the previously estimated  subject-to-MNI deformation cannot be used anymore...    
> 
> How can we prevent this? Or check that things do not get inadvertently messed up?

**Comment by Remi-Gau** [comment]
won't implement unless some REALLY needs it
