### ISSUE TITLE
[BUG] Getting data from: \wsl$ still empty 

### ISSUE THREAD

**Issue by mwmaclean** [cpp-lln-lab/bidspm#653]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

Getting data from:
 \wsl$\PATH\TO\DATA

### Current Behavior

```
Getting data from:
 \wsl$
 ```
 No path is indicated in the command window
 (works for paths on the windows file system or external hard drive) 

### Error message

n/a

### Environment

```markdown
- OS:windows
- Matlab:R2019b
- SPM:12
```

### Branch

```markdown
- branch:
- version:
```

**Comment by Remi-Gau** [comment]
Does does this lead to a crash or is just that the message displayed is just:

```text
Getting data from:
 \wsl$
```

But things continue normally.

**Comment by Remi-Gau** [comment]
Hopefully this should now be fixed but reopen in case this pops up again
