### ISSUE TITLE
[BUG]Warning: FAILED : Extract data & MarsBaR estimation during bidsRoiBasedGLM: subjects skipped

### ISSUE THREAD

**Issue by mwmaclean** [cpp-lln-lab/bidspm#689]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating system

- [ ] Linux
- [ ] Mac
- [X] Windows

### Operating system version

```markdown
- Linux Ubuntu 18.04 "bionic beaver"
- Mac OS Version 12 "monterey"
```

### SPM 12 version

- [X] 7771
- [ ] 7487
- [ ] 7219

### Platform

- [ ] MATLAB
- [ ] Octave

### Platform version

```markdown
MATLAB R2019b
```

### CPP SPM version

- [X] v2.0.0
- [ ] v1.1.0
- [ ] v1.0.0
- [ ] v0.2.0
- [ ] v0.1.0
- [ ] v0.0.1

### CPP SPM branch / commit number

```markdown
- main 29b689dd
- dev 1bda0162
```

### Current Behavior

known issue : skips certain participants (e.g. here: performs roi based glm for right hemisphere but not left)

### Error message

Warning: FAILED : Extract data & MarsBaR estimation.
Skipping:
- subject: CTL13
- ROI: space-MNI_atlas-neurosynth_label-rightmidbrainnew_mask.nii
 
> In bidsRoiBasedGLM (line 98)
  In statsmidbrain (line 32) 
Warning: No data for sub-CTL13 / roi rightmidbrainnew
 
> In saveRoiGlmSummaryTable (line 63)
  In bidsRoiBasedGLM (line 180)
  In statsmidbrain (line 32)

**Comment by Remi-Gau** [comment]
Apparently this can be improved if you used AR(1) and not FAST as correction for temporal auto
correlation in the GLM.

This can be specified in Software section of the bids stats model.

```json
        "Software": {
          "SPM": {
            "SerialCorrelation": "AR(1)",
            "InclusiveMaskingThreshold": "-Inf"
          }
        }
```

**Comment by Remi-Gau** [comment]
@mwmaclean not sure if you saw / tried this fix 🆙 ☝🏾 .

**Comment by Remi-Gau** [comment]
closing for now but feel free to reopen if this is not fixed

**Comment by Remi-Gau** [comment]
should probably make a decent bug report with a MWE for marsbar
