### ISSUE TITLE
[BUG] bidsRoiBasedGLM(opt) smoothing specified partially ignored

### ISSUE THREAD

**Issue by mwmaclean** [cpp-lln-lab/bidspm#722]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating system

- [ ] Linux
- [ ] Mac
- [X] Windows

### Operating system version

```markdown
- Linux Ubuntu 18.04 "bionic beaver"
- Mac OS Version 12 "monterey"
```

### SPM 12 version

- [ ] 7771
- [ ] 7487
- [ ] 7219

### Platform

- [ ] MATLAB
- [ ] Octave

### CPP SPM version

- [ ] v2.0.0
- [ ] v1.1.0
- [ ] v1.0.0
- [ ] v0.2.0
- [ ] v0.1.0
- [ ] v0.0.1

### CPP SPM branch / commit number

```markdown
- main 29b689dd
- dev 1bda0162
```

### Expected Behavior

to run `bidsFFX('specify', opt);` and `bidsRoiBasedGLM(opt)` only for the smoothing specified and to output the files

### Current Behavior

When running 
`bidsFFX('specify', opt);` and 
`bidsRoiBasedGLM(opt)` I get the following warning:

```
Warning: No SPM.mat found for subject CTL07 in folder:
D:/cvi/outputs/derivatives/cpp_spm-stats/sub-CTL07/task-motion_space-MNI152NLin2009cAsym_FWHM-0_roi
Run bidsFFX('specify', opt)
```
the smoothing specified was `opt.fwhm.func = 8;`  and not 0
but 2 directories are created in `derivatives\cpp_spm-stats\sub-CTL07` one ending with `FWHM-0_roi` and one with `FWHM-8_roi`. 
`bidsFFX('specify', opt)` is done for the specified smoothing but not for 0.
No crash but also no output from the step: `bidsRoiBasedGLM(opt)` with the specifed smoothing of 8.
This repeats on more than one participant.

**Comment by mwmaclean** [comment]
update: the default `opt.fwhm.func = 0`; specified in `bidsRoiBasedGLM(opt)` seems to overwrite at this step what is specified both in the script and in `opt = checkOptions(opt);`

**Comment by Remi-Gau** [comment]
I think we fixed this one but feel free to reopen if that's not the case

**Comment by mwmaclean** [comment]
yes I think this was fixed :)
