### ISSUE TITLE
wrong TR is shown in commander window during slice timing

### ISSUE THREAD

**Issue by yyang1234** [cpp-lln-lab/bidspm#763]
Hi, when I run the slicing time during preprocessing, the TR shown in the command window is 3.5s, twice as large as the actual TR (1.75s). 
It might because that in line 99 of ```setBatchSTC.m```, nbslice is calculated by finding the unique slice time: 
```nbSlices = numel(unique(sliceOrder));```

My data used multiband,so half of them had the same slice time as the other half. So nbslice only gets half of the actual slice number.

unique is necessary in case of multi echo.

**Comment by Remi-Gau** [comment]
This should be fixed.

Will close after one final check and adding comments to explain better why some things are done this way.

**Comment by Remi-Gau** [comment]
@all-contributors please add @yyang1234 for bug, userTesting
