### ISSUE TITLE
struct variable name not updated

### ISSUE THREAD

**Issue by fcerpe** [cpp-lln-lab/bidspm#796]
https://github.com/cpp-lln-lab/bidspm/blob/22e25999d7341781efbdb4a33cc1f0f7757c49d9/src/workflows/stats/bidsResults.m#L289

`opt.model.bm.get_nodes` seems to be outdated, resulting in an error. 
stats_option outputs `opt.model.bm.Nodes`

Full error (if needed):

```matlab
Dot indexing is not supported for variables of this type.

Error in bidsResults>returnListNodeNames (line 290)
      listNodeNames{iRes} = node.Name;

Error in bidsResults>checks (line 263)
  listNodeNames = returnListNodeNames(opt);

Error in bidsResults (line 147)
  status = checks(opt);

Error in stats_localizer (line 31)
bidsResults(opt);
```

**Comment by Remi-Gau** [comment]
OK so the function that seems to fail for you is this one (from version 2.1)

https://github.com/cpp-lln-lab/bidspm/blob/v2.1.0/src/workflows/stats/bidsResults.m#L283

```matlab
function listNodeNames = returnListNodeNames(opt)

  listNodeNames = {};

  for iRes = 1:numel(opt.results)
    if ~isempty(opt.results(iRes).nodeName)
      node = opt.model.bm.get_nodes('Name',  opt.results(iRes).nodeName);
      listNodeNames{iRes} = node.Name;
    end
  end

end
```

So can you try to run it on its own by running the bit of code below to see it you can reproduce the error.

```matlab
%% TO DO
opt = function_you_use_generate_your_options();

opt.model.file = path_to_bids_stats_model;

%% TO RUN
opt.model.bm = BidsModel('file', opt.model.file);

listNodeNames = {};

for iRes = 1:numel(opt.results)
  if ~isempty(opt.results(iRes).nodeName)
    node = opt.model.bm.get_nodes('Name',  opt.results(iRes).nodeName);
    listNodeNames{iRes} = node.Name;
  end
end
```

**Comment by fcerpe** [comment]
I can reproduce the error
> Dot indexing is not supported for variables of this type.

variable `node` is empty

**Comment by Remi-Gau** [comment]
ok nice

I think I have your stats model, so can you copy the content of the function that creates your opt.

If I can reproduce it on my side then it will help fixing it.

**Comment by fcerpe** [comment]
`function opt = stats_localizer_option()
%
% returns a structure that contains the options chosen by the user to run
% slice timing correction, pre-processing, FFX, RFX.
%
% (C) Copyright 2019 Remi Gau

opt = [];

opt.subjects = {'006','007','008','009'}; % 002 003 004 005

% Task to analyze - change accordingly
opt.taskName = 'viualLocalizer';

opt.verbosity = 2;

% space to analyse
opt.space = 'MNI';

% Drastically improve analysis speed with a simple trick!  
% the F in false stands fo fast
opt.glm.QA.do = false;

% The functional smoothing 
opt.fwhm.func = 6;
opt.fwhm.contrast = 0;

% The directory where the data are located
opt.dir.root = fullfile(fileparts(mfilename('fullpath')), '..', '..');

opt.dir.raw = fullfile(opt.dir.root, 'inputs', 'raw');
opt.dir.derivatives = fullfile(opt.dir.root, 'outputs', 'derivatives');
opt.dir.preproc = fullfile(opt.dir.root, 'outputs', 'derivatives', 'cpp_spm-preproc');
opt.dir.input = opt.dir.preproc;
opt.dir.roi = fullfile(opt.dir.root, 'outputs', 'derivatives', 'cpp_spm-roi');
opt.dir.stats = fullfile(opt.dir.root, 'outputs', 'derivatives', 'cpp_spm-stats');

% Model specifies all the contrasts
opt.model.file = fullfile(opt.dir.root, 'code', ...
    'models', 'model-visualLocalizerUnivariate_smdl.json');

opt.pipeline.type = 'stats';

% Specify the result to compute
opt.results.Nodes(1) = defaultResultsStructure();

opt.results.Nodes(1).Level = 'subject';

% For each contrats, you can adapt:
%  - voxel level (p)
%  - cluster (k) level threshold
%  - type of multiple comparison:
%    - 'FWE' is the defaut
%    - 'FDR'
%    - 'none'

% nodeName = name of the Node in the BIDS stats model
opt.results(1).nodeName = 'Run';
% name of the contrast in the BIDS stats model
opt.results(1).name = {'french_gt_scrambled'};
% Specify how you want your output (all the following are on false by default)
opt.results(1).png = true();
opt.results(1).csv = true();
opt.results(1).p = 0.001;
opt.results(1).MC = 'none';
opt.results(1).k = 0;
% those don't change across contrasts, try to put only once
opt.results(1).binary = true();
opt.results(1).montage.do = true();
opt.results(1).montage.background = struct('suffix', 'T1w', 'desc', 'preproc', 'modality', 'anat');
opt.results(1).montage.slices = -20:2:0;
opt.results(1).montage.orientation = 'axial'; % also 'sagittal', 'coronal'
opt.results(1).nidm = true();
opt.results(1).threshSpm = true();

opt.results(2).nodeName = 'Run';
opt.results(2).name = {'braille_gt_scrambled'};
opt.results(2).png = true();
opt.results(2).csv = true();
opt.results(2).p = 0.001;
opt.results(2).MC = 'none';
opt.results(2).k = 0;
% those don't change across contrasts, try to put only once
opt.results(2).binary = true();
opt.results(2).montage.do = true();
opt.results(2).montage.background = struct('suffix', 'T1w', 'desc', 'preproc', 'modality', 'anat');
opt.results(2).montage.slices = -20:2:0;
opt.results(2).montage.orientation = 'axial'; % also 'sagittal', 'coronal'
opt.results(2).nidm = true();
opt.results(2).threshSpm = true();

opt.results(3).nodeName = 'Run';
opt.results(3).name = {'drawing_gt_scrambled'};
opt.results(3).png = true();
opt.results(3).csv = true();
opt.results(3).p = 0.001;
opt.results(3).MC = 'none';
opt.results(3).k = 0;
% those don't change across contrasts, try to put only once
opt.results(3).binary = true();
opt.results(3).montage.do = true();
opt.results(3).montage.background = struct('suffix', 'T1w', 'desc', 'preproc', 'modality', 'anat');
opt.results(3).montage.slices = -20:2:0;
opt.results(3).montage.orientation = 'axial'; % also 'sagittal', 'coronal'
opt.results(3).nidm = true();
opt.results(3).threshSpm = true();

opt.results(4).nodeName = 'Run';
opt.results(4).name = {'frWords_gt_scrLines'};
opt.results(4).png = true();
opt.results(4).csv = true();
opt.results(4).p = 0.001;
opt.results(4).MC = 'none';
opt.results(4).k = 0;
% those don't change across contrasts, try to put only once
opt.results(4).binary = true();
opt.results(4).montage.do = true();
opt.results(4).montage.background = struct('suffix', 'T1w', 'desc', 'preproc', 'modality', 'anat');
opt.results(4).montage.slices = -20:2:0;
opt.results(4).montage.orientation = 'axial'; % also 'sagittal', 'coronal'
opt.results(4).nidm = true();
opt.results(4).threshSpm = true();

opt.results(5).nodeName = 'Run';
opt.results(5).name = {'allWords_gt_scrLines'};
opt.results(5).png = true();
opt.results(5).csv = true();
opt.results(5).p = 0.001;
opt.results(5).MC = 'none';
opt.results(5).k = 0;
% those don't change across contrasts, try to put only once
opt.results(5).binary = true();
opt.results(5).montage.do = true();
opt.results(5).montage.background = struct('suffix', 'T1w', 'desc', 'preproc', 'modality', 'anat');
opt.results(5).montage.slices = -20:2:0;
opt.results(5).montage.orientation = 'axial'; % also 'sagittal', 'coronal'
opt.results(5).nidm = true();
opt.results(5).threshSpm = true();



% Specify how you want your output (all the following are on false by default)


%% DO NOT TOUCH
opt = checkOptions(opt);
saveOptions(opt);

end
`

**Comment by Remi-Gau** [comment]
OK you don't have Node named `Run` in your model and you are trying to plot the results from
`opt.results(1).nodeName = 'Run';`

Either change the name of the node in the model to `Run` or change things in opt.results so all node names are somethings like `opt.results(1).nodeName = 'localizer GLM';`

**Comment by Remi-Gau** [comment]
Was the error preceded by a warning telling you that it could not find a corresponding node?

Will try to improve the warning content.

```matlab
Warning:
Could not find a corresponding Node.
 
> In bids.internal.error_handling (line 57)
  In bids.Model/get_nodes (line 335)
  In untitled2 (line 9) 
Dot indexing is not supported for variables of this type.

Error in untitled2 (line 10)
    listNodeNames{iRes} = node.Name;
```
