### ISSUE TITLE
[BUG] Cannot index trial types if they are all numeric

### ISSUE THREAD

**Issue by JeanLucAnton** [cpp-lln-lab/bidspm#800]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating system

- [ ] Linux
- [x] Mac
- [ ] Windows

### Operating system version

```markdown
- Mac OS Version 12 "monterey"
```

### SPM 12 version

- [x] 7771
- [ ] 7487
- [ ] 7219

### Platform

- [x] MATLAB
- [ ] Octave

### bidspm version

v2.1.0

### bidspm branch / commit number

```markdown
- main 29b689dd
- dev 1bda0162
```

### Current Behavior

...

### Error message

```matlab
Brace indexing is not supported for variables of this type.

Error in bids.internal.list_all_trial_types (line 26)
        trial_type_list{end + 1, 1} = tmp.trial_type{j}; %#ok<*AGROW>

Error in bids.Model/default (line 737)
      trial_type_list = bids.internal.list_all_trial_types(args.Results.layout, tasks);

Error in createDefaultStatsModel (line 71)
  bm = bm.default(BIDS);
```

**Comment by Remi-Gau** [comment]
this is a bids matlab issue, will resolve on that repo
