### ISSUE TITLE
[BUG]  error from spmup?

### ISSUE THREAD

**Issue by marcobarilari** [cpp-lln-lab/bidspm#845]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating system

- [ ] Linux
- [X] Mac
- [ ] Windows

### Operating system version

- Mac OS Version 13.0.1 "ventura"

### SPM 12 version

- [ ] 7771
- [X] 7487
- [ ] 7219

### Platform

- [X] MATLAB
- [ ] Octave

### Platform version

- MATLAB 2017b

### bidspm version

v2.3.0

### bidspm branch / commit number

- HEAD 59566e5e

### Expected Behavior

to run my preprocessing analyses

### Current Behavior & Error message

```matlab
% this is the error I got

-----------------------------------
 1st level QA - processing data /[...]/outputs/derivatives/bidspm-preproc/sub-pilot001/ses-001/func/usub-pilot001_ses-001_task-audioV1_run-001_bold.nii 
-----------------------------------
Defaults settings have been modified by file(s):
  /[...]/code/src/../lib/bidspm/src/defaults/spm_my_defaults.m
Modified fields: ui mat stats realign 
Error: File: spm_load.m Line: 189 Column: 1
All functions in a script must be closed with an 'end'.

Error in spmup_realign_qa (line 227)
    all_regressors = spm_load(new_files{findex});

Error in spmup_first_level_qa (line 104)
[realign_files,jobs.FD,jobs.glo] = spmup_realign_qa(time_series,...

Error in functionalQA (line 147)
          outputFiles = spmup_first_level_qa(funcImage, ...

Error in bidsSpatialPrepro (line 141)
    functionalQA(opt);

```

**Comment by Remi-Gau** [comment]
This is strange.

I read this as an error in `spm_load`

Can you try `spm_load(some_tsv_file_on_your_computer)`?

**Comment by marcobarilari** [comment]
Yeah, for some scary reason there were some characters at the beginning of the `spm_load` script that created this error. Deleting those characters fixed it. True that the error was pointing clearly to `spm_load`.

Closing this one!
