### ISSUE TITLE
[BUG] file realignment parameters not found while it exists

### ISSUE THREAD

**Issue by avanaudenhaege** [cpp-lln-lab/bidspm#892]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating system

- [ ] Linux
- [X] Mac
- [ ] Windows

### Operating system version

- Mac OS Version 10.15.7 "Catalina"

### SPM 12 version

- [X] 7771
- [ ] 7487
- [ ] 7219

### Platform

- [X] MATLAB
- [ ] Octave

### Platform version

- MATLAB R2017b

### bidspm version

v2.3.0

### bidspm branch / commit number

- main 59566e5e

### Expected Behavior

Running preprocessing on one subject (sub-04), the script stops after normalisation. 

SPM is unable to read the file '/Users/alice/Documents/DATA/LipSpeechPilot_analysis/LipSpeech_BIDS/derivatives/bidspm-preproc/sub-04/ses-01/func/rp_sub-04_ses-01_task-MVPAAud_run-01_space-individual_desc-stc_bold.txt
'
error coming from line 31 in spm_load :

 ```
~exist(f,'file')
    error('Unable to read file ''%s''',f);
end 
```
while this file is indeed in the correct folder with the correct name. 
<img width="938" alt="Capture d’écran 2022-12-22 à 10 53 04" src="https://user-images.githubusercontent.com/75271651/209107723-1e0ab402-af07-4317-a4d2-4a28f2659a4f.png">

Running the same preprocessing script in the same environment with another subject (sub-03) works fine.

### Current Behavior & Error message

```matlab
Error using spm_load (line 31)
Unable to read file
'/Users/alice/Documents/DATA/LipSpeechPilot_analysis/LipSpeech_BIDS/derivatives/bidspm-preproc/sub-04/ses-01/func/rp_sub-04_ses-01_task-MVPAAud_run-01_space-individual_desc-stc_bold.txt
'

Error in convertRealignParamToTsv (line 33)
  content = spm_load(rpTxtFile);

Error in bidsSpatialPrepro>renameFiles (line 176)
          convertRealignParamToTsv(rpFiles(iFile, :), opt, rmInput);

Error in bidsSpatialPrepro (line 144)
  renameFiles(BIDS, opt);

Error in bidspm>preprocess (line 232)
    bidsSpatialPrepro(opt);

Error in bidspm>executeAction (line 134)
      preprocess(args);

Error in bidspm (line 73)
    executeAction(action, args);

Error in step_1_preprocess (line 25)
bidspm(bids_dir, output_dir, 'subject', ...

```

### Anything else?

[error_2022-12-22T10-19.log](https://github.com/cpp-lln-lab/bidspm/files/10285719/error_2022-12-22T10-19.log)
[rp_sub-04_ses-01_task-MVPAAud_run-01_space-individual_desc-stc_bold.txt](https://github.com/cpp-lln-lab/bidspm/files/10287591/rp_sub-04_ses-01_task-MVPAAud_run-01_space-individual_desc-stc_bold.txt)

**Comment by Remi-Gau** [comment]
Thanks for the big report.

2 quick things.

Is this a datalad dataset?

If so make sure the txt file is unlocked.

**Comment by avanaudenhaege** [comment]
No it's not !

**Comment by Remi-Gau** [comment]
And the content of the txt file looks normal?

Can you maybe add it to the issue?

**Comment by avanaudenhaege** [comment]
Yes it looks normal, it's in the extra info

**Comment by Remi-Gau** [comment]
OK I can open the file locally by doing: 

`spm_load rp_sub-04_ses-01_task-MVPAAud_run-01_space-individual_desc-stc_bold.txt`

If you try to run the line that failed when running the workflow, does it still fail?

```
spm_load('/Users/alice/Documents/DATA/LipSpeechPilot_analysis/LipSpeech_BIDS/derivatives/bidspm-preproc/sub-04/ses-01/func/rp_sub-04_ses-01_task-MVPAAud_run-01_space-individual_desc-stc_bold.txt')
```

**Comment by avanaudenhaege** [comment]
No, it works if I do only spm_load
<img width="1298" alt="Capture d’écran 2022-12-22 à 19 54 55" src="https://user-images.githubusercontent.com/75271651/209206651-dfcc079f-e644-4fb7-9aae-6e70246f1fe7.png">

**Comment by avanaudenhaege** [comment]
To be more precise : 
When I am in debug mode, 
`spm_load(rpTxtFile)` doesn't work.
But if I copy paste manually the string from `rpTxtFile`  then it is found by spm_load
see here under : 
`rpTxtFile =

    '/Users/alice/Documents/DATA/LipSpeechPilot_analysis/LipSpeech_BIDS/derivatives/bidspm-preproc/sub-04/ses-01/func/rp_sub-04_ses-01_task-MVPAVis_run-01_space-individual_desc-stc_bold.txt '

K>> spm_load(rpTxtFile)
Error using spm_load (line 31)
Unable to read file
'/Users/alice/Documents/DATA/LipSpeechPilot_analysis/LipSpeech_BIDS/derivatives/bidspm-preproc/sub-04/ses-01/func/rp_sub-04_ses-01_task-MVPAVis_run-01_space-individual_desc-stc_bold.txt
'
 
K>> spm_load('/Users/alice/Documents/DATA/LipSpeechPilot_analysis/LipSpeech_BIDS/derivatives/bidspm-preproc/sub-04/ses-01/func/rp_sub-04_ses-01_task-MVPAVis_run-01_space-individual_desc-stc_bold.txt')

ans =

         0         0         0         0         0         0
    0.0104    0.0044   -0.0286   -0.0000   -0.0001    0.0002
    0.0077   -0.0075   -0.0255   -0.0000   -0.0001    0.0001
    0.0121    0.0021   -0.0460   -0.0001   -0.0002    0.0003
    0.0157    0.0004   -0.0597   -0.0002   -0.0001    0.0004
    0.0093   -0.0292   -0.0098   -0.0002   -0.0001    0.0001
    0.0149   -0.0250   -0.0120   -0.0004   -0.0002    0.0004
    0.0081   -0.0225    0.0529   -0.0017   -0.0003    0.0002
    0.0040   -0.0222    0.0615   -0.0016   -0.0002    0.0002
    ... `

**Comment by Remi-Gau** [comment]
Need to check but it seems for some reason the filename seems to have an extra '\n' at the end.

**Comment by avanaudenhaege** [comment]
What is strange is that the error is specific to 1 of my 2 subjects

**Comment by Remi-Gau** [comment]
Non systematic bugs are amongst the most annoying.
Will try to add a "fix" but without a reproducible bug it may be a zombie bug.
One that comes back from the grave even if you think it is dead.

**Comment by Remi-Gau** [comment]
Added what should be a fix in the dev branch, so if you change branch you should be able to test it.

**Comment by Remi-Gau** [comment]
Well at least it should fix the first part of not finding the realignment parameters. Not sure about the unwarping parameter file.

**Comment by Remi-Gau** [comment]
Well at least it should fix the first part of not finding the realignment parameters. Not sure about the unwarping parameter file.
