### ISSUE TITLE
[ENH] Add in the doc how to not name a condition or a contrast to make bidsResults work

### ISSUE THREAD

**Issue by marcobarilari** [cpp-lln-lab/bidspm#973]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Unclear documentation

I have in my event file for example `condition_1` and `condition_2` and contrast `conditions` and `cond_1_gt_cond_2`.

When running the results workflow, it fails since the code is set to:

line 387 of `bidsResults.m`

``` 
% skip contrast with name ending in _[0-9]* as they are run level
% contrasts
```

So, I might suggest adding somewhere (FAQ? A warning within bidspm?) that naming a contrast `*_a-number` is not a good idea.

The behavior now is either 

1. in case it is asked to print only 1 contrast, the process does not start cause matlabbatch is empty, or 

2. in case of multiple contrasts where one is named "correctly" and the other is not it just thrown an error that `field dir does not exist` (if you want to know more about this error LMK cause it is a bit long to write here and not sure it is relevant)

ps: I lied, I did not check if an issue exists already OR if it is already written somewhere 😇

**Comment by Remi-Gau** [comment]
a potential fix would be to name run wise contrast:
- condition_1_run-1 
- condition_1_run-2
- condition_2_run-1 
- condition_2_run-2 

this way the "filtering" can be done by skipping things that end in `_run-[0-9]*` rather than just `_[0-9]*`

**Comment by Remi-Gau** [comment]
On seconds thought I think your suggestion may be better: especially that you can easily rename the conditions in your TSV using variable transformation in the BIDS stats model

https://github.com/bids-standard/variable-transform/blob/main/spec/munge.md#replace
