### ISSUE TITLE
Requesting more documentation

### ISSUE THREAD

**Issue by iqrashahzad14** [cpp-lln-lab/bidspm#996]
Can we please have more description of how the output of the Group level stats will look like? 
https://bidspm.readthedocs.io/en/latest/method_section.html
I did not find more details on this webpage. If there is already, can you please point me towards it ? 😉

**Comment by Remi-Gau** [comment]
if it were somewhere to be found it would be there: https://bidspm.readthedocs.io/en/latest/output_files.html#statistics

But indeed this is too sparse at the moment
